#Bricata API Client: Example Configuration
#Copyright Â© 2019 Jerod Gawne <https://github.com/jerodg/>
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the Server Side Public License (SSPL) as
#published by MongoDB, Inc., either version 1 of the
#License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#SSPL for more details.
#
#You should have received a copy of the SSPL along with this program.
#If not, see <https://www.mongodb.com/licensing/server-side-public-license>.
[Auth]  # Required
    Username = ""
    Password = ""

[URI]
    Base = ""  # Required; Should not include trailing /

[Options]
    CAPath = ""  # Full path to Certificate Authority file
    VerifySSL = true  # Default true

[Proxy]  # Optional
    URI = ""
    Port = ""
    Username = ""
    Password = ""
